<?php

namespace Database\Seeders;

use App\Models\AccountCategories;
use App\Models\AccountNames;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            'Cash in vault',
            'petty cash',
            'Cash in banks',
            'Cash in banks, operating',
            'Cash in banks, lending',
            'Cash in banks,savings',
            'Reserves in central bank',
            'Short-term investments',
            'Portfolio, type A',
            'Portfolio, type B',
            'Restructured loans',
            'Loan loss reserve',
            'Interest loss reserve(for accrual systems only)',
            'Interest receivable,current loans',
            'Interest receivable,nonperforming loans',
            'Interest receivable,rescheduled loans',
            'Commissions receivable',
            'Other loan fees receivable',
            'Accounts receivable',
            'Travel advances',
            'Other advances to employees',
            'Other receivables',
            'Investment A',
            'Investment B',
            'Buildings',
            'Depreciation, buildings',
            'Land',
            'Equipment',
            'Depreciation, equipment',
            'Vehicles',
            'Depreciation, vehicles',
            'Leasehold improvements',
            'Deprquirements, leasehold improvements',
            'Prepaid expenses',
            'Trade accounts payable',
            'Accounts payable, members',
            'Accounts payable, employees',
            'Interest payable, loans',
            'Interest payable, passbook savings',
            'Interest payable, time deposits',
            'Interest payable, other',
            'Collateral savings',
            'Voluntary savings',
            'Time deposits',
            'Loans payable, bank 1',
            'Loans payable, bank 2',
            'Loans payable, other',
            'Lease payable',
            'Interest on loans',
            'Bank commissions and fees',
            'Interest on client savings',
            'Other financing costs',
            'Loan loss provisions',
            'Interest loss provisions',
            'Salaries, officers',
            'Salaries, others',
            'Honoraria',
            'Payroll tax expense',
            'Health insurance',
            'Other insurance',
            'Vacation',
            'Sick leave',
            'Other benefits',
            'Other supplies',
            'Telephone and fax',
            'Postage and delivery',
            'Printing',
            'Professional fees',
            'Auditing and accounting fees',
            'Legal fees',
            'Other office expenses',
            'Insurance',
            'Rent',
            'Utilities',
            'Maintenance and cleaning',
            'Airfare',
            'Public ground transportation',
            'Vehicle operating expenses',
            'Lodging costs',
            'Meals and incidentals',
            'Transport of goods',
            'Storage',
            'Miscellaneous travel costs',
            'Equipment rental',
            'Equipment maintenance',
            'Equipment deprication',
            'Vehicle deprication',
            'Leasehold amortization',
            'Instructional materials and supplies',
            'Books and publications',
            'Technical assistance',
            'Continuing education',
            'Entertainment',
            'Gain/(loss) on sale of investments',
            'Gain/(loss) on sale of assets',
            'Federal taxes paid',
            'Other taxes paid',
            'Other'
        ];

        $codes = [
            1000,
            1005,
            1010,
            1011,
            1012,
            1013,
            1050,
            1100,
            1210,
            1220,
            1240,
            1310,
            1320,
            1410,
            1420,
            1440,
            1450,
            1459,
            1510,
            1520,
            1525,
            1530,
            1610,
            1612,
            1710,
            1711,
            1720,
            1730,
            1731,
            1740,
            1741,
            1750,
            1751,
            1810,
            2010,
            2012,
            2014,
            2110,
            2120,
            2130,
            2150,
            2210,
            2220,
            2230,
            2320,
            2322,
            2330,
            2350,
            5010,
            5014,
            5020,
            5030,
            5110,
            5120,
            5210,
            5212,
            5214,
            5220,
            5230,
            5232,
            5240,
            5242,
            5250,
            5310,
            5312,
            5314,
            5316,
            5320,
            5322,
            5324,
            5330,
            5332,
            5410,
            5420,
            5430,
            5510,
            5514,
            5516,
            5520,
            5530,
            5540,
            5542,
            5550,
            5610,
            5620,
            5630,
            5640,
            5650,
            5710,
            5730,
            5740,
            5810,
            5820,
            5910,
            5920,
            5930,
            5940,
            5990,
        ];

        $count = count($accounts);
        for ($i = 0; $i < $count; $i++) {
            $account_name = $accounts[$i];
            $code = $codes[$i];
            AccountNames::create([
                'code' => $code,
                'name' => $account_name
            ]);
        }

        $account_categories = [
            'Cash and equivalents',
            'Loan portfolio',
            'Reserve for possible losses',
            'Interest and fees receivable',
            'Receivables',
            'Long-term investments',
            'Property and equipment',
            'Other assets',
            'Payables',
            'Interest payable',
            'Client deposits',
            'Loans payable, short term',
            'Financing expenses',
            'Loss provisions',
            'Personnel expenses',
            'Office expenses',
            'Occupancy expenses',
            'Travel costs',
            'Equipment',
            'Program expenses',
            'Miscellaneous expenses',
            'Nonoperating income and expenses'

        ];

        $category_codes = [
            1000,
            1200,
            1300,
            1400,
            1500,
            1600,
            1700,
            1800,
            2000,
            2100,
            2200,
            2300,
            5000,
            5100,
            5200,
            5300,
            5400,
            5500,
            5600,
            5700,
            5800,
            5900
        ];

        $count = count($account_categories);
        for ($i = 0; $i < $count; $i++) {
            $account_name = $account_categories[$i];
            $code = $category_codes[$i];
            AccountCategories::create([
                'code' => $code,
                'name' => $account_name
            ]);
        }
    }
}
